// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDETB-Fs-cA2H5uKl7Sv7doc30Jn2f0Z_A',
    appId: '1:466158715074:web:91e2dbf619715b116a7b5b',
    messagingSenderId: '466158715074',
    projectId: 'health-app-dd419',
    authDomain: 'health-app-dd419.firebaseapp.com',
    storageBucket: 'health-app-dd419.firebasestorage.app',
    measurementId: 'G-VN0SEGSEZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOnErkc7WmlPM-fE53Upju6OBq8IGjrzU',
    appId: '1:466158715074:android:58e1c23b4b2226d06a7b5b',
    messagingSenderId: '466158715074',
    projectId: 'health-app-dd419',
    storageBucket: 'health-app-dd419.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCErRy04T1pZHcP4krTbv0nSbeQJkIfhDA',
    appId: '1:466158715074:ios:0bd30177146a312f6a7b5b',
    messagingSenderId: '466158715074',
    projectId: 'health-app-dd419',
    storageBucket: 'health-app-dd419.firebasestorage.app',
    iosBundleId: 'com.example.healthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCErRy04T1pZHcP4krTbv0nSbeQJkIfhDA',
    appId: '1:466158715074:ios:0bd30177146a312f6a7b5b',
    messagingSenderId: '466158715074',
    projectId: 'health-app-dd419',
    storageBucket: 'health-app-dd419.firebasestorage.app',
    iosBundleId: 'com.example.healthapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDETB-Fs-cA2H5uKl7Sv7doc30Jn2f0Z_A',
    appId: '1:466158715074:web:0660968189a524076a7b5b',
    messagingSenderId: '466158715074',
    projectId: 'health-app-dd419',
    authDomain: 'health-app-dd419.firebaseapp.com',
    storageBucket: 'health-app-dd419.firebasestorage.app',
    measurementId: 'G-V6RGLCBLBR',
  );
}
